import { JWT } from 'google-auth-library';
import { GoogleSpreadsheet } from 'google-spreadsheet';

export const getDoc = async (sheetName: string) => {
  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
  const doc = new GoogleSpreadsheet(process.env.SHEET_ID, serviceAccountAuth);

  await doc.loadInfo();

  if (!sheetName) {
    return doc;
  }
  const sheet = doc.sheetsByTitle[sheetName]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
  return sheet;
};
